import {
    BlockExplodeAfterEvent,
    ButtonPushAfterEvent,
    ChatSendAfterEvent,
    ChatSendBeforeEvent,
    DataDrivenEntityTriggerAfterEvent,
    EffectAddAfterEvent,
    EffectAddBeforeEvent,
    EntityDieAfterEvent,
    EntityHealthChangedAfterEvent,
    EntityHitBlockAfterEvent,
    EntityHitEntityAfterEvent,
    EntityHurtAfterEvent,
    EntityLoadAfterEvent,
    EntityRemoveAfterEvent,
    EntityRemoveBeforeEvent,
    EntitySpawnAfterEvent,
    ExplosionAfterEvent,
    ExplosionBeforeEvent,
    GameRuleChangeAfterEvent,
    ItemCompleteUseAfterEvent,
    ItemReleaseUseAfterEvent,
    ItemStartUseAfterEvent,
    ItemStartUseOnAfterEvent,
    ItemStopUseAfterEvent,
    ItemStopUseOnAfterEvent,
    ItemUseAfterEvent,
    ItemUseBeforeEvent,
    ItemUseOnAfterEvent,
    ItemUseOnBeforeEvent,
    LeverActionAfterEvent,
    MessageReceiveAfterEvent,
    PistonActivateAfterEvent,
    PlayerBreakBlockAfterEvent,
    PlayerBreakBlockBeforeEvent,
    PlayerDimensionChangeAfterEvent,
    PlayerEmoteAfterEvent,
    PlayerGameModeChangeAfterEvent,
    PlayerGameModeChangeBeforeEvent,
    PlayerInputPermissionCategoryChangeAfterEvent,
    PlayerInteractWithBlockAfterEvent,
    PlayerInteractWithBlockBeforeEvent,
    PlayerInteractWithEntityAfterEvent,
    PlayerInteractWithEntityBeforeEvent,
    PlayerJoinAfterEvent,
    PlayerLeaveAfterEvent,
    PlayerLeaveBeforeEvent,
    PlayerPlaceBlockAfterEvent,
    PlayerPlaceBlockBeforeEvent,
    PlayerSpawnAfterEvent,
    PressurePlatePopAfterEvent,
    PressurePlatePushAfterEvent,
    ProjectileHitBlockAfterEvent,
    ProjectileHitEntityAfterEvent,
    TargetBlockHitAfterEvent,
    TripWireTripAfterEvent,
    WeatherChangeAfterEvent,
    WeatherChangeBeforeEvent,
    world,
    WorldInitializeAfterEvent,
    WorldInitializeBeforeEvent,
} from "@minecraft/server";

const EventMappings = {
    WorldInitializeAfterEvent: WorldInitializeAfterEvent,
    GameRuleChangeAfterEvent: GameRuleChangeAfterEvent,
    MessageReceiveAfterEvent: MessageReceiveAfterEvent,
    WeatherChangeAfterEvent: WeatherChangeAfterEvent,
    ChatSendAfterEvent: ChatSendAfterEvent,
    ButtonPushAfterEvent: ButtonPushAfterEvent,
    LeverActionAfterEvent: LeverActionAfterEvent,
    PlayerPlaceBlockAfterEvent: PlayerPlaceBlockAfterEvent,
    BlockExplodeAfterEvent: BlockExplodeAfterEvent,
    ExplosionAfterEvent: ExplosionAfterEvent,
    PlayerBreakBlockAfterEvent: PlayerBreakBlockAfterEvent,
    EntityLoadAfterEvent: EntityLoadAfterEvent,
    EntitySpawnAfterEvent: EntitySpawnAfterEvent,
    DataDrivenEntityTriggerAfterEvent: DataDrivenEntityTriggerAfterEvent,
    EffectAddAfterEvent: EffectAddAfterEvent,
    ProjectileHitEntityAfterEvent: ProjectileHitEntityAfterEvent,
    ProjectileHitBlockAfterEvent: ProjectileHitBlockAfterEvent,
    EntityHitEntityAfterEvent: EntityHitEntityAfterEvent,
    EntityHitBlockAfterEvent: EntityHitBlockAfterEvent,
    EntityHurtAfterEvent: EntityHurtAfterEvent,
    EntityHealthChangedAfterEvent: EntityHealthChangedAfterEvent,
    EntityDieAfterEvent: EntityDieAfterEvent,
    EntityRemoveAfterEvent: EntityRemoveAfterEvent,
    ItemStartUseOnAfterEvent: ItemStartUseOnAfterEvent,
    ItemUseOnAfterEvent: ItemUseOnAfterEvent,
    ItemUseAfterEvent: ItemUseAfterEvent,
    ItemStopUseOnAfterEvent: ItemStopUseOnAfterEvent,
    ItemStartUseAfterEvent: ItemStartUseAfterEvent,
    ItemCompleteUseAfterEvent: ItemCompleteUseAfterEvent,
    ItemReleaseUseAfterEvent: ItemReleaseUseAfterEvent,
    ItemStopUseAfterEvent: ItemStopUseAfterEvent,
    PlayerJoinAfterEvent: PlayerJoinAfterEvent,
    PlayerSpawnAfterEvent: PlayerSpawnAfterEvent,
    PlayerLeaveAfterEvent: PlayerLeaveAfterEvent,
    PlayerGameModeChangeAfterEvent: PlayerGameModeChangeAfterEvent,
    PlayerDimensionChangeAfterEvent: PlayerDimensionChangeAfterEvent,
    PlayerInputPermissionCategoryChangeAfterEvent:
        PlayerInputPermissionCategoryChangeAfterEvent,
    PlayerInteractWithEntityAfterEvent: PlayerInteractWithEntityAfterEvent,
    PlayerInteractWithBlockAfterEvent: PlayerInteractWithBlockAfterEvent,
    PistonActivateAfterEvent: PistonActivateAfterEvent,
    PressurePlatePushAfterEvent: PressurePlatePushAfterEvent,
    PressurePlatePopAfterEvent: PressurePlatePopAfterEvent,
    TargetBlockHitAfterEvent: TargetBlockHitAfterEvent,
    TripWireTripAfterEvent: TripWireTripAfterEvent,
    PlayerEmoteAfterEvent: PlayerEmoteAfterEvent,
    ChatSendBeforeEvent: ChatSendBeforeEvent,
    ExplosionBeforeEvent: ExplosionBeforeEvent,
    ItemUseBeforeEvent: ItemUseBeforeEvent,
    ItemUseOnBeforeEvent: ItemUseOnBeforeEvent,
    PlayerBreakBlockBeforeEvent: PlayerBreakBlockBeforeEvent,
    PlayerPlaceBlockBeforeEvent: PlayerPlaceBlockBeforeEvent,
    EntityRemoveBeforeEvent: EntityRemoveBeforeEvent,
    PlayerInteractWithBlockBeforeEvent: PlayerInteractWithBlockBeforeEvent,
    PlayerInteractWithEntityBeforeEvent: PlayerInteractWithEntityBeforeEvent,
    PlayerLeaveBeforeEvent: PlayerLeaveBeforeEvent,
    PlayerGameModeChangeBeforeEvent: PlayerGameModeChangeBeforeEvent,
    EffectAddBeforeEvent: EffectAddBeforeEvent,
    WeatherChangeBeforeEvent: WeatherChangeBeforeEvent,
    WorldInitializeBeforeEvent: WorldInitializeBeforeEvent,
};


export default EventMappings;
